#!/usr/bin/env bash
# ============================================================
# SMOKE — the lead path against a real `wrangler dev` (C8).
#
#   bash scripts/smoke-lead.sh
#
# Four scripted POSTs, watching the log lines the money path now
# guarantees (the runtime branches the lib harness cannot reach — AL-14
# is the real e2e harness; this script is the stand-in it replaces):
#
#   1. D1 unbound     → 503 + "[lead] REFUSED — D1 unbound"
#   2. happy path     → 200 ok:true, row in local D1
#   3. honeypot       → 200 ok:true (indistinguishable) + "[lead] honeypot drop"
#   4. bad category   → 400 "not something we sell"
#
# Phase 1 runs dev with the config AS BUILT (template: no D1 binding) to
# prove the unbound branch. Phase 2 injects a LOCAL-ONLY test binding into
# the build artifact dist/server/wrangler.json (regenerated by every
# build — nothing permanent is touched), applies migrations, and runs the
# other three.
# ============================================================
set -euo pipefail
cd "$(dirname "$0")/.."

BASE_PORT="${PORT:-8788}"
PORT="$BASE_PORT"
URL="http://127.0.0.1:$PORT"

# A stale dev server on the port answers with STALE CODE and the whole run
# lies. Each phase claims the first genuinely free port instead.
pick_port() {
  for p in $(seq "$BASE_PORT" $((BASE_PORT + 20))); do
    if ! curl -s -m 1 -o /dev/null "http://127.0.0.1:$p/"; then
      PORT="$p"; URL="http://127.0.0.1:$PORT"; return 0
    fi
  done
  echo "no free port in $BASE_PORT..$((BASE_PORT + 20))"; exit 1
}
CONSENT_VERSION="$(node -e "process.stdout.write(require('fs').readFileSync('src/config/consent.ts','utf8').match(/CONSENT_VERSION = '([^']+)'/)[1])")"

PASS=0; FAIL=0

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
good() { PASS=$((PASS+1)); printf '  \033[32mPASS\033[0m %s\n' "$*"; }
bad()  { FAIL=$((FAIL+1)); printf '  \033[31mFAIL\033[0m %s\n' "$*"; }

[ -d dist/server ] || { say "dist/ missing — building first"; npm run build >/dev/null; }
mkdir -p .wrangler

# `wrangler dev` persists local D1 to .wrangler/state by default; the d1
# CLI commands need the SAME path passed explicitly or they operate on a
# different database and every table quietly "does not exist".
PERSIST=".wrangler/state"

start_dev() { # $1 = phase label for the log file
  pick_port
  DEV_LOG=".wrangler/smoke-dev-$1.log"
  : > "$DEV_LOG"
  npx wrangler dev --port "$PORT" >>"$DEV_LOG" 2>&1 &
  DEV_PID=$!
  for _ in $(seq 1 60); do
    if [ "$(curl -s -o /dev/null -w '%{http_code}' "$URL/")" = "200" ]; then
      sleep 2 # let the worker finish module init before the first POST
      return 0
    fi
    sleep 1
  done
  echo "wrangler dev never became ready — log tail:"; tail -20 "$DEV_LOG"; exit 1
}
stop_dev() {
  kill "$DEV_PID" >/dev/null 2>&1 || true
  wait "$DEV_PID" 2>/dev/null || true
  # workerd sometimes outlives its parent; give the port a moment to free.
  for _ in 1 2 3 4 5; do
    curl -s -m 1 -o /dev/null "$URL/" || return 0
    sleep 1
  done
}

# Console output reaches the log file a beat after the HTTP response.
expect_log() { # $1 = pattern, $2 = label
  sleep 1
  if grep -q "$1" "$DEV_LOG"; then good "log line: $2"; else bad "missing log line: $2"; fi
}

post_lead() { # $1 = JSON body
  curl -s -w '\n%{http_code}' -X POST "$URL/api/lead" \
    -H 'Content-Type: application/json' -d "$1"
}

# ---------------------------------------------------------------
say "PHASE 1 — config as built (no D1 binding): the unbound branch"
start_dev phase1
OUT="$(post_lead '{"name":"Smoke Test","email":"smoke@example.test","phone":"6195550142","consentVersion":"'"$CONSENT_VERSION"'"}')"
CODE="${OUT##*$'\n'}"
[ "$CODE" = "503" ] && good "unbound POST → 503" || bad "unbound POST → $CODE (expected 503)"
expect_log '\[lead\] REFUSED — D1 unbound' '[lead] REFUSED — D1 unbound'
stop_dev

# ---------------------------------------------------------------
say "PHASE 2 — local test DB injected into the BUILD ARTIFACT only"
node - <<'EOF'
const fs = require('fs');
const f = 'dist/server/wrangler.json';
const c = JSON.parse(fs.readFileSync(f, 'utf8'));
c.d1_databases = [{
  binding: 'DB',
  database_name: 'smoke-local',
  database_id: '00000000-0000-0000-0000-00000000cafe',
  migrations_dir: '../../db/migrations',
}];
fs.writeFileSync(f, JSON.stringify(c, null, 2));
console.log('  injected DB binding into dist/server/wrangler.json (build artifact)');
EOF
npx wrangler d1 migrations apply DB --local --persist-to "$PERSIST" -c dist/server/wrangler.json >/dev/null 2>&1 \
  && good "migrations applied to local smoke DB" \
  || bad  "migrations apply failed"
start_dev phase2

say "2a — happy path"
OUT="$(post_lead '{"name":"Smoke Test","email":"smoke@example.test","phone":"6195550142","message":"smoke","category":"","sourcePage":"/smoke","eventId":"evt-smoke-1","consentVersion":"'"$CONSENT_VERSION"'"}')"
CODE="${OUT##*$'\n'}"; BODY="${OUT%$'\n'*}"
[ "$CODE" = "200" ] && echo "$BODY" | grep -q '"ok":true' \
  && good "lead accepted → 200 ok:true" || bad "happy path → $CODE $BODY"
ROW="$(npx wrangler d1 execute DB --local --persist-to "$PERSIST" -c dist/server/wrangler.json \
  --command "SELECT first_name, consent_version FROM leads ORDER BY created_at DESC LIMIT 1" --json 2>/dev/null)"
echo "$ROW" | grep -q '"first_name": *"Smoke"' && echo "$ROW" | grep -q "\"consent_version\": *\"$CONSENT_VERSION\"" \
  && good "row in D1 with consent_version=$CONSENT_VERSION" \
  || bad  "D1 row missing or consent not recorded: $ROW"

say "2b — honeypot (server-side)"
OUT="$(post_lead '{"name":"Bot Bot","email":"bot@example.test","phone":"6195550142","company":"Totally Real LLC","consentVersion":"'"$CONSENT_VERSION"'"}')"
CODE="${OUT##*$'\n'}"; BODY="${OUT%$'\n'*}"
[ "$CODE" = "200" ] && echo "$BODY" | grep -q '"ok":true' \
  && good "bot got fake success → 200 ok:true" || bad "honeypot → $CODE $BODY"
expect_log '\[lead\] honeypot drop' '[lead] honeypot drop'

say "2c — category outside the allowlist"
OUT="$(post_lead '{"name":"Smoke Test","email":"smoke@example.test","phone":"6195550142","category":"submarine","consentVersion":"'"$CONSENT_VERSION"'"}')"
CODE="${OUT##*$'\n'}"
[ "$CODE" = "400" ] && good "bad category → 400" || bad "bad category → $CODE (expected 400)"

stop_dev

# ---------------------------------------------------------------
say "RESULT: $PASS passed · $FAIL failed"
say "Relevant dev-log lines:"
grep -E '\[lead\]|\[capi\]|\[ghl\]|\[stage\]' "$DEV_LOG" | sed 's/^/  /' || true
[ "$FAIL" = "0" ]
